site_name: pages
site_url: https://fleetinglore.github.io/pages/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  # 代码块相关扩展
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - javascripts/katex-init.js